# Generated by Django 5.0.6 on 2024-09-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmei_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codTurma', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTurma', models.CharField(max_length=20)),
                ('observacaoTurma', models.CharField(max_length=100)),
                ('cmei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmei_app.cmei')),
            ],
        ),
    ]
