# Generated by Django 5.0.6 on 2024-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('codCrianca', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCrianca', models.CharField(max_length=100)),
                ('dataNascCrianca', models.DateField()),
                ('nomeResponsavel', models.CharField(max_length=100)),
                ('telefoneResponsavel', models.CharField(max_length=11)),
                ('emailResponsavel', models.CharField(max_length=100)),
                ('cpfResponsavel', models.CharField(max_length=11)),
                ('dataInicialCadastro', models.DateField()),
                ('dataFinalCadastro', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(max_length=100)),
                ('nomeUsuario', models.CharField(max_length=100)),
            ],
        ),
    ]
