# Generated by Django 5.0.6 on 2024-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMEI',
            fields=[
                ('codCmei', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCmei', models.CharField(max_length=100)),
            ],
        ),
    ]
