# Generated by Django 5.0.6 on 2024-09-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crianca_app', '0001_initial'),
        ('turma_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateField(auto_now_add=True)),
                ('dataSaida', models.DateField(blank=True, null=True)),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('criterio', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('nao_confirmado', 'Não Confirmado')], default='nao_confirmado', max_length=20)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crianca_app.crianca')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma_app.turma')),
            ],
        ),
    ]
