# Generated by Django 5.0.6 on 2024-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
